//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.GrantApplicationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GrantApplicationService.IGrantApplicationService")]
    public interface IGrantApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGrantApplicationService/ReviewApplication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ReviewApplication(string ApplicationId, bool PassedReview);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGrantApplicationService/ReviewApplication")]
        System.Threading.Tasks.Task ReviewApplicationAsync(string ApplicationId, bool PassedReview);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrantApplicationService/ApplyForGrant", ReplyAction="http://tempuri.org/IGrantApplicationService/ApplyForGrantResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="applicationId")]
        ServiceClient.GrantApplicationService.ApplyForGrantResponse ApplyForGrant(ServiceClient.GrantApplicationService.ApplyForGrantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrantApplicationService/ApplyForGrant", ReplyAction="http://tempuri.org/IGrantApplicationService/ApplyForGrantResponse")]
        System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.ApplyForGrantResponse> ApplyForGrantAsync(ServiceClient.GrantApplicationService.ApplyForGrantRequest request);
        
        // CODEGEN: Generating message contract since the operation TerminateJobApplication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGrantApplicationService/TerminateJobApplication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TerminateJobApplication(ServiceClient.GrantApplicationService.TerminateJobApplication request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGrantApplicationService/TerminateJobApplication")]
        System.Threading.Tasks.Task TerminateJobApplicationAsync(ServiceClient.GrantApplicationService.TerminateJobApplication request);
        
        // CODEGEN: Generating message contract since the operation GetGrantApplicationStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrantApplicationService/GetGrantApplicationStatus", ReplyAction="http://tempuri.org/IGrantApplicationService/GetGrantApplicationStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1 GetGrantApplicationStatus(ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrantApplicationService/GetGrantApplicationStatus", ReplyAction="http://tempuri.org/IGrantApplicationService/GetGrantApplicationStatusResponse")]
        System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1> GetGrantApplicationStatusAsync(ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JobApplicationService")]
    public partial class GrantApplication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Grantee applyingGranteeField;
        
        private string grantTypeIdField;
        
        private string orgIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Grantee ApplyingGrantee {
            get {
                return this.applyingGranteeField;
            }
            set {
                this.applyingGranteeField = value;
                this.RaisePropertyChanged("ApplyingGrantee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string GrantTypeId {
            get {
                return this.grantTypeIdField;
            }
            set {
                this.grantTypeIdField = value;
                this.RaisePropertyChanged("GrantTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string OrgId {
            get {
                return this.orgIdField;
            }
            set {
                this.orgIdField = value;
                this.RaisePropertyChanged("OrgId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JobApplicationService")]
    public partial class Grantee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailAddressField;
        
        private string granteeIdField;
        
        private string orgNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string GranteeId {
            get {
                return this.granteeIdField;
            }
            set {
                this.granteeIdField = value;
                this.RaisePropertyChanged("GranteeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string OrgName {
            get {
                return this.orgNameField;
            }
            set {
                this.orgNameField = value;
                this.RaisePropertyChanged("OrgName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/JobApplicationService")]
    public partial class GrantApplicationStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string grantApplicationIdField;
        
        private string grantTypeAppliedForField;
        
        private bool passedReviewField;
        
        private bool passedReviewFieldSpecified;
        
        private bool passedRiskAssessmentField;
        
        private bool passedRiskAssessmentFieldSpecified;
        
        private GrantApplication submittedApplicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GrantApplicationId {
            get {
                return this.grantApplicationIdField;
            }
            set {
                this.grantApplicationIdField = value;
                this.RaisePropertyChanged("GrantApplicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string GrantTypeAppliedFor {
            get {
                return this.grantTypeAppliedForField;
            }
            set {
                this.grantTypeAppliedForField = value;
                this.RaisePropertyChanged("GrantTypeAppliedFor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool PassedReview {
            get {
                return this.passedReviewField;
            }
            set {
                this.passedReviewField = value;
                this.RaisePropertyChanged("PassedReview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PassedReviewSpecified {
            get {
                return this.passedReviewFieldSpecified;
            }
            set {
                this.passedReviewFieldSpecified = value;
                this.RaisePropertyChanged("PassedReviewSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PassedRiskAssessment {
            get {
                return this.passedRiskAssessmentField;
            }
            set {
                this.passedRiskAssessmentField = value;
                this.RaisePropertyChanged("PassedRiskAssessment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PassedRiskAssessmentSpecified {
            get {
                return this.passedRiskAssessmentFieldSpecified;
            }
            set {
                this.passedRiskAssessmentFieldSpecified = value;
                this.RaisePropertyChanged("PassedRiskAssessmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public GrantApplication SubmittedApplication {
            get {
                return this.submittedApplicationField;
            }
            set {
                this.submittedApplicationField = value;
                this.RaisePropertyChanged("SubmittedApplication");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyForGrant", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyForGrantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceClient.GrantApplicationService.GrantApplication application;
        
        public ApplyForGrantRequest() {
        }
        
        public ApplyForGrantRequest(ServiceClient.GrantApplicationService.GrantApplication application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyForGrantResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ApplyForGrantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string applicationId;
        
        public ApplyForGrantResponse() {
        }
        
        public ApplyForGrantResponse(string applicationId) {
            this.applicationId = applicationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TerminateJobApplication {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        public TerminateJobApplication() {
        }
        
        public TerminateJobApplication(string guid) {
            this.guid = guid;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetGrantApplicationStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GrantApplicationStatus currentGrantApplicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GrantApplicationStatus CurrentGrantApplication {
            get {
                return this.currentGrantApplicationField;
            }
            set {
                this.currentGrantApplicationField = value;
                this.RaisePropertyChanged("CurrentGrantApplication");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGrantApplicationStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        public GetGrantApplicationStatusRequest() {
        }
        
        public GetGrantApplicationStatusRequest(string guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGrantApplicationStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse GetGrantApplicationStatusResponse;
        
        public GetGrantApplicationStatusResponse1() {
        }
        
        public GetGrantApplicationStatusResponse1(ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse GetGrantApplicationStatusResponse) {
            this.GetGrantApplicationStatusResponse = GetGrantApplicationStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrantApplicationServiceChannel : ServiceClient.GrantApplicationService.IGrantApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrantApplicationServiceClient : System.ServiceModel.ClientBase<ServiceClient.GrantApplicationService.IGrantApplicationService>, ServiceClient.GrantApplicationService.IGrantApplicationService {
        
        public GrantApplicationServiceClient() {
        }
        
        public GrantApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrantApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrantApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrantApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReviewApplication(string ApplicationId, bool PassedReview) {
            base.Channel.ReviewApplication(ApplicationId, PassedReview);
        }
        
        public System.Threading.Tasks.Task ReviewApplicationAsync(string ApplicationId, bool PassedReview) {
            return base.Channel.ReviewApplicationAsync(ApplicationId, PassedReview);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.GrantApplicationService.ApplyForGrantResponse ServiceClient.GrantApplicationService.IGrantApplicationService.ApplyForGrant(ServiceClient.GrantApplicationService.ApplyForGrantRequest request) {
            return base.Channel.ApplyForGrant(request);
        }
        
        public string ApplyForGrant(ServiceClient.GrantApplicationService.GrantApplication application) {
            ServiceClient.GrantApplicationService.ApplyForGrantRequest inValue = new ServiceClient.GrantApplicationService.ApplyForGrantRequest();
            inValue.application = application;
            ServiceClient.GrantApplicationService.ApplyForGrantResponse retVal = ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).ApplyForGrant(inValue);
            return retVal.applicationId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.ApplyForGrantResponse> ServiceClient.GrantApplicationService.IGrantApplicationService.ApplyForGrantAsync(ServiceClient.GrantApplicationService.ApplyForGrantRequest request) {
            return base.Channel.ApplyForGrantAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.ApplyForGrantResponse> ApplyForGrantAsync(ServiceClient.GrantApplicationService.GrantApplication application) {
            ServiceClient.GrantApplicationService.ApplyForGrantRequest inValue = new ServiceClient.GrantApplicationService.ApplyForGrantRequest();
            inValue.application = application;
            return ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).ApplyForGrantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ServiceClient.GrantApplicationService.IGrantApplicationService.TerminateJobApplication(ServiceClient.GrantApplicationService.TerminateJobApplication request) {
            base.Channel.TerminateJobApplication(request);
        }
        
        public void TerminateJobApplication(string guid) {
            ServiceClient.GrantApplicationService.TerminateJobApplication inValue = new ServiceClient.GrantApplicationService.TerminateJobApplication();
            inValue.guid = guid;
            ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).TerminateJobApplication(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ServiceClient.GrantApplicationService.IGrantApplicationService.TerminateJobApplicationAsync(ServiceClient.GrantApplicationService.TerminateJobApplication request) {
            return base.Channel.TerminateJobApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task TerminateJobApplicationAsync(string guid) {
            ServiceClient.GrantApplicationService.TerminateJobApplication inValue = new ServiceClient.GrantApplicationService.TerminateJobApplication();
            inValue.guid = guid;
            return ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).TerminateJobApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1 ServiceClient.GrantApplicationService.IGrantApplicationService.GetGrantApplicationStatus(ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest request) {
            return base.Channel.GetGrantApplicationStatus(request);
        }
        
        public ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse GetGrantApplicationStatus(string guid) {
            ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest inValue = new ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest();
            inValue.guid = guid;
            ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1 retVal = ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).GetGrantApplicationStatus(inValue);
            return retVal.GetGrantApplicationStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1> ServiceClient.GrantApplicationService.IGrantApplicationService.GetGrantApplicationStatusAsync(ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest request) {
            return base.Channel.GetGrantApplicationStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.GrantApplicationService.GetGrantApplicationStatusResponse1> GetGrantApplicationStatusAsync(string guid) {
            ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest inValue = new ServiceClient.GrantApplicationService.GetGrantApplicationStatusRequest();
            inValue.guid = guid;
            return ((ServiceClient.GrantApplicationService.IGrantApplicationService)(this)).GetGrantApplicationStatusAsync(inValue);
        }
    }
}
